# Generated by Django 4.1.1 on 2022-10-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('variant', models.CharField(choices=[('G', 'Green'), ('B', 'Blue'), ('R', 'Red')], default=0, max_length=1)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skin')),
            ],
        ),
    ]
